# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='cabinet_no',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='cabinet_pos',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='disk_info',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='hostname_raw',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='number',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='public_ip',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='remote_card_ip',
        ),
    ]
